// flow-typed signature: 841f5b15c0727a6076254e0127c3ca45
// flow-typed version: <<STUB>>/react-confetti_v^2.6.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-confetti'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-confetti' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-confetti/dist/react-confetti' {
  declare module.exports: any;
}

declare module 'react-confetti/dist/react-confetti.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-confetti/dist/react-confetti.js' {
  declare module.exports: $Exports<'react-confetti/dist/react-confetti'>;
}
declare module 'react-confetti/dist/react-confetti.min.js' {
  declare module.exports: $Exports<'react-confetti/dist/react-confetti.min'>;
}
declare module 'react-confetti/index' {
  declare module.exports: $Exports<'react-confetti'>;
}
declare module 'react-confetti/index.js' {
  declare module.exports: $Exports<'react-confetti'>;
}
