// flow-typed signature: 1457b2a443448523208a04d95f196c9a
// flow-typed version: <<STUB>>/react-waypoint_v^9.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-waypoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-waypoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-waypoint/cjs/index' {
  declare module.exports: any;
}

declare module 'react-waypoint/es/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-waypoint/cjs/index.js' {
  declare module.exports: $Exports<'react-waypoint/cjs/index'>;
}
declare module 'react-waypoint/es/index.js' {
  declare module.exports: $Exports<'react-waypoint/es/index'>;
}
